### ISSUE TITLE
Aptik not starting with GUI.

### ISSUE THREAD

**Issue by abalter** [teejee2008/aptik-legacy#17]
I just installed Aptik and it won't start in GUI mode. I've tried running it from the application launch window as well as the command line. When I launch it from the command line, I just get the command line help.

I'm doing this in the Windows Subsystem for Linux (WSL). I'm using the IceWM desktop in a VNC session. All other GUI applications that I try work fine. I even installed Synaptic and reinstalled Aptik from there.

Incidentally, I'd be happy to work from the command line, but there isn't much documentation on how to do the exact same things I would do using the GUI.

**Comment by teejee2008** [comment]
Type aptik-gtk in a terminal. Post the error message if it does not start.

**Comment by abalter** [comment]
That worked!

**Comment by jyapujuju** [comment]
No protocol specified
Unable to init server: Could not connect: Connection refused

(aptik-gtk:2201): Gtk-WARNING **: cannot open display: :0
