### ISSUE TITLE
Message dialog dimensions

### ISSUE THREAD

**Issue by atareao** [teejee2008/aptik-legacy#19]
All the message dialogs look like this.

![captura de pantalla de 2017-10-12 07-23-55](https://user-images.githubusercontent.com/298055/31480496-675b92ee-af1e-11e7-9764-6764c32dfb92.png)

**Comment by teejee2008** [comment]
Issue is with newer versions of Gtk. Will be fixed in the next update.

**Comment by teejee2008** [comment]
Fixed in v17.10
