### ISSUE TITLE
Allow alternative/additional backup paths

### ISSUE THREAD

**Issue by arderyp** [teejee2008/aptik-legacy#4]
Allow user to enter alternative/additional paths to backup, as DejaDup does.  Sometimes we want more than just our home directory.

**Comment by teejee2008** [comment]
Aptik is not meant to replace DejaDup. DejaDup is a standard backup utility that can handle large amounts of data and save them to offline and cloud accounts. Aptik is not meant to be used for this.

**Comment by arderyp** [comment]
okay.  Feel free to close this then.
