### ISSUE TITLE
Package backup fails when backup path has a space character in file path

### ISSUE THREAD

**Issue by arderyp** [teejee2008/aptik-legacy#6]
This is from an email I sent last month.  I didn't see anything in the v17.3.1 release notes about it, so I am assuming it's still a problem.  Feel free to close if it has been fixed but wasn't documented.

There is a bug that prevents the packages backup from succeeding if the destination has a space in it's file path.  I checked the packages plist and did see some packages there, but running Aptik resulted in some rsync errors about "no such file or directory" because it was attempting to reach `/path/to/my` instead of `/path/to/my\ file`.  None of the other backup processes threw errors, just the packages backup.  Regardless, the process continued and finished.  Once I renamed my file path to exclude the spaces, the packages backup runs smoothly.

**Comment by teejee2008** [comment]
Fixed in v17.10
